apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-search-pydeps
  namespace: lab-domains-sre
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
