apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen3-235b-thinking-cache
  namespace: lab-domains-sre
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 320Gi
  storageClassName: local-path
