apiVersion: v1
kind: Service
metadata:
  name: domains-embeddings
  namespace: lab-domains-sre
spec:
  type: ClusterIP
  selector:
    app: embeddings-ollama
  ports:
    - name: ollama
      port: 11434
      targetPort: 11434
      protocol: TCP
