apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: embeddings-ollama-data
  namespace: lab-domains-sre
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
