apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgvector-data
  namespace: lab-domains-sre
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
