apiVersion: v1
kind: Service
metadata:
  name: domains-pgvector
  namespace: lab-domains-sre
spec:
  type: ClusterIP
  selector:
    app: pgvector
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
