apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen3-32b-thinking-aicompute03-cache
  namespace: lab-domains-sre
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
  storageClassName: local-path
